### ISSUE TITLE
init : proxy DN different form cert DN : authentication on cert DN fails

### ISSUE THREAD

**Issue by adriansev** [italiangrid/voms-clients#21] opened 2019-02-03 10:03 UTC
Hi! I see that when doing init, the subject of proxy have an added CN=<some number>
Is this required? can it be disabled? how can i make an https server that authenticate my DN to also authenticate my voms proxy DN?
Thank you!!

**Comment by andreaceccanti** [comment] 2019-02-04 11:38
The additional CN is required. 
To properly support VOMS proxy certificates your HTTP server (or web application) should be configured to enable proxy certificate and voms attribute certificate validation and information.
This is usually either done having direct voms support in the app (integrating with voms APIs) or by having a reverse proxy in front of your app and leveraging, as an example, apache  mod_gridsite. 

Hope this helps!
(closing since this is not a bug)

**Closed by andreaceccanti** 2019-02-04 11:38 UTC

**Comment by adriansev** [comment] 2019-02-04 12:05
Thank you!
